controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.30
    wheel_radius: 0.10

    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.8

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.5
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 2.0